// WINDOW
#define WINDOW_WIDTH 500
#define WINDOW_HEIGHT 700
char* WINDOW_TITLE = "TODOS REMINDER";

// TRUE FALSE
#define TRUE  1
#define FALSE 0

// BACKGROUND
#define BACKGROUND_COLOR_R 28
#define BACKGROUND_COLOR_G 28
#define BACKGROUND_COLOR_B 28

// TASK CONSTANTS
#define TASK_MAX_COUNT 50

#define TASK_HEIGHT 80
#define TASK_WIDTH 450
#define TASK_SPACE_BETWEEN 20
#define TASK_SPACE_SIDE 20

#define TASK_TEXT_COLOR_R 255
#define TASK_TEXT_COLOR_G 255
#define TASK_TEXT_COLOR_B 255

#define TASK_TITLE_CHAR_COUNT 20
#define TASK_TITLE_X 50
#define TASK_TITLE_Y 50

#define TASK_DETAIL_CHAR_COUNT 500

#define TASK_MINI_DETAIL_CHAR_COUNT 55
#define TASK_MINI_DETAIL_X 50
#define TASK_MINI_DETAIL_Y 15

// TEMPO

#define TASK_TICK_BUTTON_UNCOMPLETE_R 150
#define TASK_TICK_BUTTON_UNCOMPLETE_G 0
#define TASK_TICK_BUTTON_UNCOMPLETE_B 0

#define TASK_TICK_BUTTON_COMPLETE_R 0
#define TASK_TICK_BUTTON_COMPLETE_G 150
#define TASK_TICK_BUTTON_COMPLETE_B 0

#define TASK_TICK_BUTTON_X 20
#define TASK_TICK_BUTTON_Y 40
#define TASK_TICK_BUTTON_R 13

#define TASK_DETAIL_BUTTON_X 270
#define TASK_DETAIL_BUTTON_Y 45
#define TASK_DETAIL_BUTTON_W 80
#define TASK_DETAIL_BUTTON_H 25

#define TASK_FAV_BUTTON_X 385
#define TASK_FAV_BUTTON_Y 57
#define TASK_FAV_BUTTON_R 12

#define TASK_REMOVE_BUTTON_X 425
#define TASK_REMOVE_BUTTON_Y 57
#define TASK_REMOVE_BUTTON_R 12

#define TASK_COLOR_R 42
#define TASK_COLOR_G 42
#define TASK_COLOR_B 42

// SLIDER CONSTANTS
#define SLIDER_BG_COLOR_R 46
#define SLIDER_BG_COLOR_G 46
#define SLIDER_BG_COLOR_B 46
#define SLIDER_HANDLE_COLOR_R 159
#define SLIDER_HANDLE_COLOR_G 159
#define SLIDER_HANDLE_COLOR_B 159

